// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSSyv7SAJ7klf0XCf2FW_g1Ru47y1xAAM',
    appId: '1:481739383143:web:cf3b85ce828a239bdf8fc2',
    messagingSenderId: '481739383143',
    projectId: 'marketplace-12ea3',
    authDomain: 'marketplace-12ea3.firebaseapp.com',
    storageBucket: 'marketplace-12ea3.firebasestorage.app',
    measurementId: 'G-LVWB4WJR23',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB7dHACNKZtEkajbFv-eLIKSyBMNP8ksc',
    appId: '1:481739383143:android:7b172e6197bd494adf8fc2',
    messagingSenderId: '481739383143',
    projectId: 'marketplace-12ea3',
    storageBucket: 'marketplace-12ea3.firebasestorage.app',
  );


  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkt4K-lRrIQSjOUPHDceeRiALQfKNSmxw',
    appId: '1:481739383143:ios:038cf600b41fe0f5df8fc2',
    messagingSenderId: '481739383143',
    projectId: 'marketplace-12ea3',
    storageBucket: 'marketplace-12ea3.firebasestorage.app',
    iosBundleId: 'com.example.boookMarketplace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkt4K-lRrIQSjOUPHDceeRiALQfKNSmxw',
    appId: '1:481739383143:ios:038cf600b41fe0f5df8fc2',
    messagingSenderId: '481739383143',
    projectId: 'marketplace-12ea3',
    storageBucket: 'marketplace-12ea3.firebasestorage.app',
    iosBundleId: 'com.example.boookMarketplace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSSyv7SAJ7klf0XCf2FW_g1Ru47y1xAAM',
    appId: '1:481739383143:web:05150c6a87212d03df8fc2',
    messagingSenderId: '481739383143',
    projectId: 'marketplace-12ea3',
    authDomain: 'marketplace-12ea3.firebaseapp.com',
    storageBucket: 'marketplace-12ea3.firebasestorage.app',
    measurementId: 'G-MC8YR0VRXP',
  );

}